############################
# --- Required options --- #
############################

# Name of website
title: Mahdi

# Your name to show in the footer
author: Mahdi Sabet Kish

###############################################
# --- List of links in the navigation bar --- #
###############################################
# You can add more pages here like "Publications" or "Projects" later
navbar-links:
  About Me: "aboutme"
  Publications: "publications"
  Education: "education" 
  Research: "research"
  Teaching: "teaching"
  Honors & Awards: "honors"
  Certifications: "certifications"
  # To add a blog page, create a file named `blog.md` and uncomment the following line
  # Blog: "blog" 

################
# --- Logo --- #
################

# To add your profile picture, upload an image to the /assets/img/ folder
# and then uncomment the next line and change the path.
avatar: "/assets/img/Mahdi_Sabet_Kish_500.jpg"

# By default, the image is cut into a circle. You can disable this by setting 'round-avatar: false'
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

# Add your information to the following links.
# To find your Google Scholar ID, go to your profile and look at the URL.
# It will be something like `.../citations?user=XXXXXXXXXXXX`. Copy the part after `user=`.
social-network-links:
  email: "mahdi.sabetkish@gmail.com"  # Replace with your actual email
  github: "mahdisabetkish"
  google-scholar: "VGUoU24AAAAJ" # Replace with your ID
  # linkedin: your-linkedin-username # You can add your LinkedIn username here

# If you want your website to generate an RSS feed, provide a description
rss-description: The personal and academic website of Mahdi Sabet Kish.

###########################
# --- General options --- #
###########################

# How to display the link to your website in the footer
url-pretty: "mahdisabetkish.github.io"

# Add the website title to the title of every page
title-on-all-pages: true

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "Asia/Tehran"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189############################
# --- Required options --- #
############################

# Name of website
title: Mahdi Sabet Kish

# Your name to show in the footer
author: Mahdi Sabet Kish

###############################################
# --- List of links in the navigation bar --- #
###############################################
# You can add more pages here like "Publications" or "Projects" later
navbar-links:
  About Me: "aboutme"
  Publications: "publications"
  Education: "education" 
  Research: "research"
  Teaching: "teaching"
  Honors & Awards: "honors"
  Certifications: "certifications"

  # To add a blog page, create a file named `blog.md` and uncomment the following line
  # Blog: "blog" 

################
# --- Logo --- #
################

# To add your profile picture, upload an image to the /assets/img/ folder
# and then uncomment the next line and change the path.
# avatar: "/assets/img/your-photo.jpg"

# By default, the image is cut into a circle. You can disable this by setting 'round-avatar: false'
round-avatar: true

#####################################
# --- Footer social media links --- #
#####################################

# Add your information to the following links.
# To find your Google Scholar ID, go to your profile and look at the URL.
# It will be something like `.../citations?user=XXXXXXXXXXXX`. Copy the part after `user=`.
social-network-links:
  email: "mahdi.sabetkish@gmail.com"  # Replace with your actual email
  github: "mahdisabetkish"
  google-scholar: "VGUoU24AAAAJ" # Replace with your ID
  # linkedin: your-linkedin-username # You can add your LinkedIn username here

# If you want your website to generate an RSS feed, provide a description
rss-description: The personal and academic website of Mahdi Sabet Kish.

###########################
# --- General options --- #
###########################

# How to display the link to your website in the footer
url-pretty: "mahdisabetkish.github.io"

# Add the website title to the title of every page
title-on-all-pages: true

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

#################################################################################
# --- You don't need to touch anything below here (but you can if you want) --- #
#################################################################################

# Output options (more information on Jekyll's site)
timezone: "Asia/Tehran"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
